### ISSUE TITLE
Api docs link broken

### ISSUE THREAD

**Issue by gabisurita** [s-panferov/valico#28]
Try  http://rustless.org/valico/doc/valico/

**Comment by MitchellBerry** [comment]
This just links to the home page and it's not clear where to find them.

Alternative is https://docs.rs/valico/3.2.0

**Comment by anentropic** [comment]
the rustless.org link goes through to some cryptocurrency site

I'm assuming this project is dead?

**Comment by s-panferov** [comment]
rustless itself is dead, but helper libraries are not. I should've fix the links, will try to find some time at the weekend

**Comment by s-marios** [comment]
rustless links are still dead. 
Also, library documentation is ..sparse to say the least (after cargo doc --open, I have no clue to where I should be looking at) .
