### ISSUE TITLE
draft-06 / draft-07 support?

### ISSUE THREAD

**Issue by handrews** [s-panferov/valico#32]
Hi from the JSON Schema spec project!  Are you planning to implement any of the newer drafts in this project?  We are reorganizing the lists on json-schema.org to highlight projects supporting (or working on supporting) draft-06 or later.

See http://json-schema.org/specification.html for info on the latest published drafts.

**Comment by s-panferov** [comment]
@handrews I'm not working actively with JSON validation right now, so it's unlikely that it will be implemented by me in the near future. But maybe someone from the community will contribute, so I'll leave the issue open.

**Comment by handrews** [comment]
@s-panferov I quite understand- thanks for tagging it, hopefully someone will step up!

**Comment by s-panferov** [comment]
draft-06 should be supported by valico v3.0.0 with help of @ramonsnir

**Comment by luyao0412** [comment]
Any update on this issue? Thanks.
