### ISSUE TITLE
3.2.0 is not sem-ver compatible with 3.1.0

### ISSUE THREAD

**Issue by nagisa** [s-panferov/valico#62]
Yesterday valico released 3.2.0 with updated dependencies. One of the dependencies updated is `url` which went from `1` to `2`.

Sadly, this seems to have been a breaking change in the public API as `url::Url` is exposed in the pubic API such as the [`Schema::resolve`](https://docs.rs/valico/3.2.0/valico/json_schema/scope/struct.Scope.html#method.resolve) method.

And so code like the following will fail to compile after a `cargo update`:

```
extern crate url; // 1.* series
extern crate valico; // 3.* series

Scope::resolve(unimplemented!(), url::Url::parse("hello").unwrap());

// error[E0308]: mismatched types
//    --> src/test.rs
//     |
// 403 |             .resolve(&msg_schema_url)
//     |                      ^^^^^^^^^^^^^^^ expected struct `url::Url`, found a different struct `url::Url`
//     |
//     = note: expected reference `&url::Url` (struct `url::Url`)
//                found reference `&url::Url` (struct `url::Url`)
//     = note: perhaps two different versions of crate `url` are being used?
```

We should yank 3.2.0 and consider releasing 4.0.

**Comment by s-panferov** [comment]
Oops, I overlooked this. I'll fix it as soon as I get a chance, thanks!
