### ISSUE TITLE
Remove uritemplate as dependency

### ISSUE THREAD

**Issue by JordiPolo** [s-panferov/valico#70]
Valico 3.5 has added a dependency to [rust-uritemplate](https://github.com/chowdhurya/rust-uritemplate).

This project seems abandoned and it brings in multiple old version of libraries. With the result that now projects including valico need to install a ton of new libraries, for instance an 0.x version of regex while the whole ecosystem is on 1.x already, etc. 
There is a [PR to update the project](https://github.com/chowdhurya/rust-uritemplate/pull/6) but does not seem that there is a maintainer for it anymore.

**Comment by agavrilov** [comment]
Better to use [uritemplate-next](https://crates.io/crates/uritemplate-next) which is an updated version of rust-uritemplate

**Comment by izolyomi** [comment]
I've just hit the same issue, it now causes problems in a wasm environment.
Are there any plans to solve this, e.g. by accepting the linked PR?
